global:
scrape_configs:
  - job_name: 'loki-query-frontend'
    scrape_interval: 1s
    static_configs:
    - targets: ['localhost:3100']
  - job_name: 'loki-distributor'
    scrape_interval: 1s
    static_configs:
    - targets: ['localhost:3100']
  - job_name: 'loki-ingester'
    scrape_interval: 1s
    static_configs:
    - targets: ['localhost:3100']
  - job_name: 'loki-querier'
    scrape_interval: 1s
    static_configs:
    - targets: ['localhost:3100']
